STRENGTH_TO_KILL_TURTLE = 5
TRIES_OF_MILT_REPLICATION = 3
CHANCE_FOR_PLANT_TO_REPLICATE = 33  # divide 1 by this num and multiply by 100%
AGE_TO_REPLICATE = 5
GUARANA_BOOST_VAL = 3
PLANT_INIT = 0

DEFAULT_Y = 20
DEFAULT_X = 20

BELLADONNA_STRENGTH = 99
BELLADONNA_NAME = "Wilcza jagoda"
BELLADONNA_SIGN = '~'

FOX_STRENGTH = 3
FOX_INIT = 7
FOX_NAME = "Lis"
FOX_SIGN = 'l'

GRASS_STRENGTH = 0
GRASS_NAME = "Trawa"
GRASS_SIGN = '#'

GUARANA_STRENGTH = 0
GUARANA_NAME = "Guarana"
GUARANA_SIGN = '*'

HUMAN_STRENGTH = 5
HUMAN_INIT = 4
HUMAN_NAME = "Czlowiek"
HUMAN_SIGN = 'h'
DURATION_OF_ABILITY = 6
COOLDOWN_OF_ABILITY = 5

MILT_STRENGTH = 0
MILT_NAME = "Mlecz"
MILT_SIGN = '&'

SHEEP_STRENGTH = 4
SHEEP_INIT = 4
SHEEP_NAME = "Owca"
SHEEP_SIGN = 'o'

SOSHOGWEED_STRENGTH = 10
SOSHOGWEED_NAME = "Barsz Sosnowskiego"
SOSHOGWEED_SIGN = '0'

TURTLE_STRENGTH = 2
TURTLE_INIT = 1
TURTLE_NAME = "Zlow"
TURTLE_SIGN = 'z'

WOLF_STRENGTH = 9
WOLF_INIT = 5
WOLF_NAME = "Wilk"
WOLF_SIGN = 'w'

MECHSHEEP_STRENGTH = 11
MECHSHEEP_INIT = 4
MECHSHEEP_NAME = "Mechaniczna Owca"
MECHSHEEP_SIGN = 'm'
